### ISSUE TITLE
Fix failing unit test

### ISSUE THREAD

**Issue by mssalvatore** [guardicode/serpentarium#1]
## Description

`test_multiprocessing_plugin_isolation()` is failing:

https://github.com/guardicode/serpentarium/blob/9b3472eccd036e1e5227eb073a013518a0f81c73/tests/test_plugin_loader.py#L50-L64

If the below script is run manually, it functions as expected

```python
from serpentarium import PluginLoader  # This needs to be first
from pathlib import Path

SERPENTARIUM_REPO = "YOUR REPO PATH HERE"

def run_plugins():
    plugin_loader = PluginLoader(Path(f"{SERPENTARIUM_REPO}/tests/plugins"))
    plugin1 = plugin_loader.load_multiprocessing_plugin(plugin_name="plugin1")
    plugin2 = plugin_loader.load_multiprocessing_plugin(plugin_name="plugin2")

    plugin1.start()
    plugin2.start()

    plugin1.join()
    plugin2.join()
    print(plugin1.return_value)
    print(plugin2.return_value)

    p1 = plugin_loader.load(plugin_name="plugin1")
    p2 = plugin_loader.load(plugin_name="plugin2")

    print()
    print(p1.run())
    print(p2.run())

    print()
    print(p1.run())
    print(p2.run())


if __name__ == "__main__":
    run_plugins()
```

There's no immediately obvious difference between the unit test and the test script that would account for the error, other than that the unit test is being run with `pytest`.

Figure out why the test fails and fix it.

It may have something to do with https://docs.python.org/3/reference/import.html#the-module-cache
>Beware though, as if you keep a reference to the module object, invalidate its cache entry in [sys.modules](https://docs.python.org/3/library/sys.html#sys.modules), and then re-import the named module, the two module objects will not be the same. By contrast, [importlib.reload()](https://docs.python.org/3/library/importlib.html#importlib.reload) will reuse the same module object, and simply reinitialise the module contents by rerunning the module’s code.

## ** UPDATE **

The plot thickens! When you run the test by itself with `pytest -k test_multiprocessing_plugin_isolation` it passes. It's only when you run the whole suite with `pytest` that the test fails.

**Comment by ilija-lazoroski** [comment]
I get three failing tests instead of that one. All of them are failing with the same message and all of them run separately passed.

<img width="1778" alt="image" src="https://user-images.githubusercontent.com/15820737/220611814-bc399ef6-4402-4b25-8154-3ebd010deb9d.png">
